name: wikirl-gym
channels:
- pytorch
dependencies:
- python=3.8
  #- anaconda
  #- cudatoolkit=10.
- numpy==1.20.3
- gym==0.18.3
- mujoco-py==2.1.2.14
- torch==1.9
- transformers==4.12.5
- wandb==0.9.1
