name: mine
channels:
- conda-forge
dependencies:
- python=3.8.10
- pip
- pip:
  - pytorch_lightning==0.8.5
  - matplotlib==3.1.2
  - numpy==1.17.4
  - tqdm==4.41.0
  - torch==1.4.0
  - torchvision==0.5.0
  - scikit_learn==0.22.1
  - Pillow<7