name: wikirl-gym
channels:
- conda-forge
dependencies:
- python=3.8.10
- pip
- pip:
  - gym==0.18.3
  - mujoco-py==2.1.2.14
  - numpy==1.20.3
  - torch==1.11.0
  - transformers==4.12.0
  - wandb==0.12.17
  - kmeans-pytorch==0.3
  - torch-semiring-einsum==1.0.0
